### ISSUE TITLE
Network-related metrics

### ISSUE THREAD

**Issue by mhoangvslev** [GDD-Nantes/FedShop#62]
- We need to measure the number of ASK, the number of requests and the quantity of data transferred.
- Instead of modifying each engine, we shall use a proxy that records these metrics.

**Comment by mhoangvslev** [comment]
A forward-proxy is implemented using Flask + Unicorn. Testing with RSA engine

**Comment by momo54** [comment]
Not a good idea. Flask is not parallel + multithread.

**Comment by mhoangvslev** [comment]
@momo54 I implemented a working prototype in Java using Spring Framework. Still need to be stress-tested.
https://github.com/mhoangvslev/FedShop-proxy
